version: "3.8"

# Rust build mode: [debug, release]
x-build-mode: &build-mode
  release

volumes:
  data-request: {}
  data-complete: {}
  redis: {}

x-shared-environment: &shared-environment
  environment:
    CONFIG.REQUEST_STORAGE_PATH: /data/request
    CONFIG.COMPLETE_STORAGE_PATH: /data/complete
    CONFIG.REDIS_URL: redis://redis
    CONFIG.BIND_ADDRESS: 0.0.0.0:3030
  volumes:
    - data-request:/data/request
    - data-complete:/data/complete

services:
  redis:
    image: redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    volumes:
      - redis:/data

  bot:
    depends_on: [ redis ]
    build:
      context: ./
      dockerfile: jigsaw-bot/Dockerfile
      args:
        BUILD_MODE: *build-mode
    restart: always
    env_file: [ .env ]
    <<: *shared-environment

  generator:
    depends_on: [ redis ]
    build:
      context: ./
      dockerfile: jigsaw-generator/Dockerfile
      args:
        BUILD_MODE: *build-mode
    restart: always
    env_file: [ .env ]
    <<: *shared-environment
    volumes:
      - data-request:/data/request
      - data-complete:/data/complete

  backend:
    depends_on: [ redis ]
    build:
      context: ./
      dockerfile: ./jigsaw-backend/Dockerfile
      args:
        BUILD_MODE: *build-mode
    restart: always
    env_file: [ .env ]
    <<: *shared-environment
    volumes:
      - data-request:/data/request
      - data-complete:/data/complete
    ports:
      - "3030:3030"
